.TH PKT2MAIL 1 "PKT-to-MAIL v0.2"
.SH NAME
pkt2mail \- sends FTN packets by email
.SH SYNTAX
.TP
.B pkt2mail
No commandline options are needed
.SH DESCRIPTION
PKT2MAIL will mime encode and send by email any FTN echomail packet that has
a \fBnormal\fP, \fBdirect\fP, or \fBcrash\fP echomail flavour in fidoconfig
(see \fBfidoconfig\fP) and any netmail packet marked as \fBcrash\fP.
It is very usefull if you don't want to pay an expensive phone bill because
of long distance calls.
.SH BUGS
Please send them to kuroshivo@bigfoot.com
.SH AUTHOR
German Theler - kuroshivo@bigfoot.com
